### ISSUE TITLE
[feature] 회의록 내용을 카테고리 별로 분류

### ISSUE THREAD

**Issue by janghw0126** [janghw0126/Real-Time-Collaborative-Editor#1]
## 📄 Description
- 회의록을 회의 안건, 회의 내용, 회의 결과의 세 가지 카테고리로 구분하여 작성할 수 있도록 기능을 구현합니다.
- 각각의 카테고리별 상태 메시지를 별도의 타입으로 관리하고, 실시간으로 업데이트하여 팀원들과 동기화합니다.

## ✅ TODO
- [x] 회의 안건 구현
- [x] 회의 내용 구현
- [x] 회의 결과 구현
- [x] 각 카테고리별 상태 메시지에 대해 WebSocket 메시지 타입 분리

## ✏️ ETC
- 회의 안건, 내용, 결과별 메시지가 서로 영향을 주지 않도록 WebSocket 메시지 타입을 구분하여 송수신합니다.
- WebSocket 연결을 하나로 유지하며, 프론트엔드 상태 변수에서 타입을 기준으로 카테고리를 나누어 구현이 가능한지 확인합니다. 만약 WebSocket 하나로 구현이 복잡하거나 비효율적이라면, 별도의 WebSocket 연결을 고려합니다.

## ⌛Deadline
~11.14
