### ISSUE TITLE
[feature] 회의 중간에 참여하는 사용자의 화면에 회의록 내용을 렌더링

### ISSUE THREAD

**Issue by janghw0126** [janghw0126/Real-Time-Collaborative-Editor#8]
## 📄 Description
- 회의 중간에 새로 참여하는 사용자가 현재 작성되고 있는 회의록의 내용을 그대로 볼 수 있도록 구현합니다.

## ✅ TODO
- [x] 서버 : 현재 회의록의 내용을 저장하기
- [ ] 서버 : 클라이언트가 처음 접속할 때, 현재 회의록의 내용을 포함한 메시지를 전송하기
- [x] 클라이언트 : 서버에서 받은 회의록 정보를 처리하기
- [ ] 클라이언트 : 서버에서 회의록 데이터를 받은 후, 초기 데이터를 렌더링하기

## ✏️ ETC
.

## ⌛Deadline
11.29~
